#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points
# to your load-balancer IP

domain_information ()
{
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

for subdomain in "www" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ];
    then
        domain_information "$1" "$subdomain" ]
    fi
done
