#!/usr/bin/env bash
#File transfer from our client to the server
if [$# -lt 4]
then
echo "Usage: 0-tranfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
scp -o StrictHostKeyChecking=no -i $1 $3@$2
