#!/usr/bin/env bash
#installing nginx web server
apt-get update
apt-get -y install nginx
echo "server {
listen 80;
server_name _;
location / {
echo 'Hello World!';
}
}" > /etc/sites-available/default
service nginx restart
