#!/usr/bin/env bash
#redirecting to another page
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/wwww/html/index.html
echo "server {
listen 80;
listen [::]:80 default_server;
root /var/www/html;
index index.html;
location /redirect_me{
return 301  https://www.youtube.com/watch?v=QH2-TGU1wu4;
}
}" > /etc/nginx/sites-available/default

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
