#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server
apt-get update
apt-get install -y nginx

# hostname of the server
hostname=$(hostname)

# Configuring Nginx to add custom HTTP response header
cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Served-By $hostname; # Custom header addition
        proxy_set_header Host \$http_host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

systemctl restart nginx
