#!/usr/bin/env bash
# Following configurations are also installed
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 426700-web-01 54.84.12.117 check
    server 426700-web-02 54.160.121.212 check
EOF

# Verify HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy

sudo systemctl enable haproxy

echo "HAProxy has been configured successfully."
