#!/usr/bin/env bash
# script for making fixes shorter
mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
service nginx start
