#!/usr/bin/env bash
#Bash script that displays Best School 10 times
m=1
while [ "$m" -le 10 ]
do
	if [ "$m" -eq 9 ]
	then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	m=$(( m + 1 ))
done
