#!/usr/bin/env bash
# Firewalls can not only filter requests, they can also forward them
*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT

sudo ufw reload
