#!/usr/bin/env bash
# configuration of the ssh key
Host *
    HashKnownHosts yes
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    GSSAPIAuthentication yes
    PasswordAuthentication no
    GSSAPIDelegateCredentials no
